package be.nsi.labo.jpa.labojpa.domain.enums;

public enum EvenementEnum {
    NOUVEAU_DOSSIER_ELECTRONIQUE,
    COMPLEMENT_ELECTRONIQUE,
    ERREUR_DOSSIER_NEP,
    REPONSE_NOTIFICATION_ELECTRONIQUE,
    ERREUR_ENVOI_NOTIFICATION_NOTICE,
    ERREUR_ENVOI_NOTIFICATION_NEP,
    NOTIFICATION_A_LIRE,
    REPONSE_A_REDIGER,
    REPONSE_A_VALIDER,
    REPONSE_A_CORRIGER
}
